version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_PORT=5001
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_APP=app.py
    volumes:
      - .:/app
    restart: always
